services:
  stamps-frontend:
    build:
      dockerfile: Dockerfile.dev
    image: osrogon/dev-stamps-frontend
    env_file:
      - .env
    # Mount the code for live reloading
    # volumes:
    #   - ./frontend:/usr/src/app
    ports:
      # Map container port 8080 to host port 8080
      - "8080:8080"
    # Run Flet
    command: python main.py 
    networks:
      - stamps-network

networks:
  stamps-network:
    external: true
