services:
  stamps-frontend:
    build:
      context: .
    # Name the service
    container_name: stamps-frontend
    expose:
      - 8080
    networks:
      - stamps-network

networks:
  stamps-network:
    external: true
