# Git and version control
.git
.gitignore

# Python specific
**/__pycache__/
*.pyc
*.pyo
*.pyd
venv/
.env/
*.egg-info/

# IDE and editor config
.vscode/
.idea/

# Build and test artifacts
build/
dist/
*.log
.pytest_cache/
htmlcov/  
**/test*/
logs/
pytest.ini

# Docker related
Dockerfile*
docker-compose*

# Other
**/assets/stamps