# Use a slim Python image
FROM python:3.13-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create the working directory
WORKDIR /usr/src/app

# Install dependencies
RUN pip install --upgrade pip>=25.3
COPY requirements.base.txt .
COPY requirements.dev.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.dev.txt

# Copy the entire project code
COPY . .
