# Use a slim Python image
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY requirements.base.txt .
COPY requirements.dev.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.dev.txt

# Copy only the require files
COPY . .

# Expose the port (Django dev server default)
EXPOSE 8000

# Default command (overridden by docker-compose.dev.yml)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]