# 1. Builder
############
FROM python:3.12-slim AS builder

# Set environment variables
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.base.txt .
COPY requirements.prod.txt .
RUN pip install --upgrade pip
RUN pip wheel --no-cache-dir --wheel-dir=/app/wheels -r requirements.prod.txt

# 2. Final image
################
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Create a non-root user for security
RUN groupadd --system appuser && \
    useradd --system --gid appuser appuser
WORKDIR /app

COPY --from=builder /app/wheels /tmp/wheels
RUN pip install --no-cache-dir /tmp/wheels/* && \
    rm -rf /tmp/wheels

# Copy application source code
COPY . .
RUN rm requirements.*

# Change ownership of the /app directory to the non-root user
RUN chown -R appuser:appuser /app

# Switch to the non-root user
USER appuser