services:
  stamps-backend:
    build:
      dockerfile: Dockerfile.test
      args:
        - PYTEST_ARGS="--no-header"
    image: osrogon/test-stamps-backend
    # The command runs tests and then exits
    command: sh -c "pytest $$PYTEST_ARGS"
    