[pytest]
DJANGO_SETTINGS_MODULE = _backend.settings
pythonpath = . ..
python_files = tests.py test_*.py *_test.py **/tests.py **/test_*.py
addopts = --create-db
filterwarnings =
    ignore::UserWarning:django.core.handlers.base

env = 
    D:RUNNING_TESTS=True