name: ⛔ Fix error Request
description: Fix issue
title: "[Fix]: "
labels: ["fix"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete the following information to describe your proposal

  - type: textarea
    id: fix_description
    attributes:
      label: Detailed description
      placeholder: What needs to be fixed?
    validations:
      required: true


