name: 🗂️ Chore Request
description: Add chore
title: "[Chore]: "
labels: ["chore"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete the following information to describe your proposal

  - type: textarea
    id: test_description
    attributes:
      label: Detailed description
      placeholder: What needs to be done?
    validations:
      required: true


