name: 📚 Documentation Request
description: Add/update documentation
title: "[Documentation]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete the following information to describe your proposal

  - type: textarea
    id: doc_description
    attributes:
      label: Detailed description
      placeholder: What needs to be documented or updated?
    validations:
      required: true



