name: 🧩 Feature Request
description: Suggest new project functionality
title: "[Feature]: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete the following information to describe your proposal

  - type: textarea
    id: feature_description
    attributes:
      label: Detailed description
      placeholder: What does it do? Why is it useful?
    validations:
      required: true

