name: 🚧 Test Request
description: Add unit test
title: "[Test]: "
labels: ["unit test"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete the following information to describe your proposal

  - type: textarea
    id: test_description
    attributes:
      label: Detailed description
      placeholder: What needs to be tested?
    validations:
      required: true


