"""
Django settings for _backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Load variables from environment
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9x4!-i!avu(zzevv&3j)es5og+^^z1f0ty*r2sb8zk=dzqnhhh"

JWT_SECRET = SECRET_KEY 
JWT_ALGORITHM = 'HS256'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application configuration
LOG_LEVEL="DEBUG"
LOG_FILE_NAME="backend.log"

# API Key header
API_KEY_CUSTOM_HEADER = "HTTP_X_API_KEY"

# User views
USER_VIEWS = [
    "CollectionsView",
    "CollectionsByIdView",
    "CollectionItemsView",
    "CollectionItemsByIdView",
    "ConditionTypesView",
    "ConditionTypesByIdView",
    "LocationsView",
    "LocationsByIdView",
    "LogoffView"
]

# API endpoints
COLORS_ENDPOINT="colors/"
CONFIG_ENDPOINT="config/"
COUNTRIES_ENDPOINT="countries/"
ISSUES_ENDPOINT="issues/"
LOCATIONS_ENDPOINT="locations/"
PAPER_TYPES_ENDPOINT="paper_types/"
STAMP_TYPES_ENDPOINT="stamps_type/"
STAMPS_ENDPOINT="stamps/"
YEARS_ENDPOINT="years/"
COLLECTIONS_ENDPOINT="collections/"
COLLECTION_ITEMS_ENDPOINT="collection_items/"
CONDITION_TYPES_ENDPOINT="condition_types/"
USERS_ENDPOINT = "users/"
HEALTH_ENDPOINT = "health/"
LOGIN_ENDPOINT = "login/"
LOGOFF_ENDPOINT = "logoff/"

# Documentations end points
SWAGGER_ENDPOINT="swagger/"
REDOC_ENDPOINT="redoc/"
SCHEMA_ENDPOINT="schema/"

# URLs
ADMIN_URL="admin/"
SERVER_URL_V1="stamps_server/api/v1/"

COLORS_URL_V1=f"{SERVER_URL_V1}{COLORS_ENDPOINT}"
CONFIG_URL_V1=f"{SERVER_URL_V1}{CONFIG_ENDPOINT}"
COUNTRIES_URL_V1=f"{SERVER_URL_V1}{COUNTRIES_ENDPOINT}"
ISSUES_URL_V1=f"{SERVER_URL_V1}{ISSUES_ENDPOINT}"
LOCATIONS_URL_V1=f"{SERVER_URL_V1}{LOCATIONS_ENDPOINT}"
PAPER_TYPES_URL_V1=f"{SERVER_URL_V1}{PAPER_TYPES_ENDPOINT}"
STAMP_TYPES_URL_V1=f"{SERVER_URL_V1}{STAMP_TYPES_ENDPOINT}"
STAMPS_URL_V1=f"{SERVER_URL_V1}{STAMPS_ENDPOINT}"
YEARS_URL_V1=f"{SERVER_URL_V1}{YEARS_ENDPOINT}"
COLLECTIONS_URL_V1=f"{SERVER_URL_V1}{COLLECTIONS_ENDPOINT}"
COLLECTION_ITEMS_URL_V1=f"{SERVER_URL_V1}{COLLECTION_ITEMS_ENDPOINT}"
CONDITION_TYPES_URL_V1=f"{SERVER_URL_V1}{CONDITION_TYPES_ENDPOINT}"
USERS_URL_V1=f"{SERVER_URL_V1}{USERS_ENDPOINT}"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_api_key',
    'drf_spectacular',      # For Swagger documentation
    "config_api",           # All APIs for the config table
    "stamp_types_api",      # All APIs for the stamp type table
    "locations_api",        # All APIs for the location table
    "paper_types_api",      # All APIs for the paper type table
    "countries_api",        # All APIs for the country table
    "colors_api",           # All APIs for the color table
    "stamps_api",           # All APIs for the stamp table
    "issues_api",           # All APIs for the table issue
    "years_api",            # All APIs for the table year
    "collections_api",      # All APIs for the table collection
    "collection_items_api", # All APIs for the table collection item
    "condition_types_api",  # All APIs for the table condition type
    "users_api",            # All APIs for the table user
    "health_api"            # All APIs for checking the system health
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": (
        "common.core.renderers.StandardJSONRenderer",
    ),
    "EXCEPTION_HANDLER": "common.core.exceptions.custom_exception_handler",
    # This sets the default permission for ALL DRF views
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'common.core.authentication.CustomAPIKeyAuthentication',
        #'rest_framework_api_key.permissionsHasSpecificKeyName'    
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework_api_key.permissions.HasAPIKey',
        # 'rest_framework.permissions.AllowAny'
        'common.core.permissions.HasSpecificKeyName'
    ]
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Stamps App API",
    "DESCRIPTION": "API documentation for the Stamps App.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # prevents schema from being included twice
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],  # customize access
    # Future-friendly:
    "COMPONENT_SPLIT_REQUEST": True,   # better request/response separation
    "TAGS": [
        {
            "name": "Database Management",
            "description": "APIs for accessing static, foundational data like years, published issues, and the master catalog of stamps."
        },
        {
            "name": "Collection Management",
            "description": "APIs for managing collections."
        },
        {
            "name": "Config Management",
            "description": "Endpoints for managing system configuration settings."
        },
        {
            "name": "User Management",
            "description": "APIs for managing users."  
        }
    ],
    # "SCHEMA_PATH_PREFIX": "/api/v1",   # useful if versioning your API
    "SWAGGER_UI_SETTINGS": {
        "defaultModelsExpandDepth": -1,
        'deepLinking': True,
        'persistAuthorization': True,
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
