"""
Django settings for _backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

# Load variables from environment
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9x4!-i!avu(zzevv&3j)es5og+^^z1f0ty*r2sb8zk=dzqnhhh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

API_KEY_CUSTOM_HEADER = "HTTP_X_API_KEY"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_api_key',
    'drf_spectacular',      # For Swagger documentation
    "config_api",           # All APIs for the config table
    "stamp_types_api",      # All APIs for the stamp type table
    "locations_api",        # All APIs for the location table
    "paper_types_api",      # All APIs for the paper type table
    "countries_api",        # All APIs for the country table
    "colors_api",           # All APIs for the color table
    "stamps_api",           # All APIs for the stamp table
    "issues_api",           # All APIs for the table issue
    "years_api",            # All APIs for the table year
    "collections_api",      # All APIs for the table collection
    "collection_items_api"  # All APIs for the table collection item
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": (
        "common.core.renderers.StandardJSONRenderer",
    ),
    "EXCEPTION_HANDLER": "common.core.exceptions.custom_exception_handler",
    # This sets the default permission for ALL DRF views
    'DEFAULT_AUTHENTICATION_CLASSES': [ ],
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework_api_key.permissions.HasAPIKey',
        'common.core.permissions.HasSpecificKeyName'
    ]
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Stamps App API",
    "DESCRIPTION": "API documentation for the Stamps App.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # prevents schema from being included twice
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],  # customize access
    # Future-friendly:
    "COMPONENT_SPLIT_REQUEST": True,   # better request/response separation
    "SECURITY": [
        {
            'APIKeyHeader': [], 
            'APINameHeader': []
        }
    ],
    "COMPONENTS": {
        'securitySchemes': {
            'APIKeyHeader': { 
                'type': 'apiKey',          # Must be 'apiKey' for header keys
                'in': 'header',            # Location in the request
                'name': 'X-API-Key',       # The RAW header name 
                'description': 'Custom API Key required for authentication.',
            },
            'APINameHeader': { 
                'type': 'apiKey',          # Must be 'apiKey' for header keys
                'in': 'header',            # Location in the request
                'name': 'X-API-User',      # The RAW header name 
                'description': 'API Key name associated the the API Key.',
            }
        }
    },
    "TAGS": [
        {
            "name": "Collections",
            "description": "Endpoints for managing collection entries. Header 'Authorizarion' required."
        },
        {
            "name": "Collection Items",
            "description": "Endpoints for managing collection item entries. Header 'Authorizarion' required."
        },
        {
            "name": "Colors",
            "description": "Endpoints for managing color entries. Headers 'X-API-Key' and 'X-API-User' required."
        },
        {
            "name": "Config",
            "description": "Endpoints for managing system configuration settings. Headers 'X-API-Key' and 'X-API-User' required."
        },
        {
            "name": "Countries",
            "description": "Endpoints for managing country entries. Headers 'X-API-Key' and 'X-API-User' required."
        },
        {
            "name": "Issues",
            "description": "Endpoints for managing issue entries. Headers 'X-API-Key' and 'X-API-User' required."
        },
        {
            "name": "Locations",
            "description": "Endpoints for managing location entries. Headers 'X-API-Key' and 'X-API-User' required."   
        },
        {
            "name": "Paper Types",
            "description": "Endpoints for managing paper types entries. Headers 'X-API-Key' and 'X-API-User' required."
        },
        {
            "name": "Stamp Types",
            "description": "Endpoints for managing stamp type entries. Headers 'X-API-Key' and 'X-API-User' required."
        },
        {
            "name": "Stamps",
            "description": "Endpoints for managing stamp entries. Headers 'X-API-Key' and 'X-API-User' required."
        },
        {
            "name": "Years",
            "description": "Endpoints for managing year entries. Headers 'X-API-Key' and 'X-API-User' required."
        }
    ],
    # "SCHEMA_PATH_PREFIX": "/api/v1",   # useful if versioning your API
    "SWAGGER_UI_SETTINGS": {
        "defaultModelsExpandDepth": -1,
        'deepLinking': True,
        'persistAuthorization': True,
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
